using System;
using System.Collections.Generic;
using System.Text;
using UnityEngine;

namespace EmberDeck.View
{
    /// <summary>Every sound effect. File names are sfx_ plus the snake_case name.</summary>
    public enum Sfx
    {
        CardDraw, CardPlay, Hit, HeavyHit, BlockedHit, BlockGain, Burn, Heat, Overheat,
        EnemyDeath, PlayerHurt, TurnStart, Victory, Defeat, Click, MapSelect, Reward,
        Upgrade, Relic, Buff, Debuff
    }

    /// <summary>Music loops. File names are music_ plus the lowercase name.</summary>
    public enum MusicTrack { None, Map, Combat, Boss }

    /// <summary>
    /// Plays every sound in the game.
    ///
    /// Clips live in Resources/Audio and are generated by art/audio/synth.py. Loading by name
    /// keeps the scene free of references to wire up, which matters in a project whose scene is
    /// itself generated from code. A missing clip is silent rather than an error: the game has
    /// to run before its audio exists.
    ///
    /// Two things stop a busy turn from turning into noise. The same effect cannot retrigger
    /// within a few milliseconds — five cards drawn at once are one draw sound, not a phaser —
    /// and effects round-robin across a fixed pool of voices, so a burst replaces its own oldest
    /// sounds instead of piling up without limit.
    /// </summary>
    public sealed class AudioDirector : MonoBehaviour
    {
        const int Voices = 10;
        const float MinRepeatGap = 0.035f;
        const float CrossfadeSeconds = 1.4f;

        public static float MasterVolume = 1f;
        public static float SfxVolume = 0.9f;
        public static float MusicVolume = 0.5f;
        public static bool Muted;

        static AudioDirector _instance;

        readonly Dictionary<Sfx, AudioClip> _clips = new();
        readonly Dictionary<Sfx, float> _lastPlayed = new();
        readonly List<AudioSource> _voices = new();
        readonly List<float> _voiceGain = new();
        int _nextVoice;

        AudioSource _music;         // the track fading in, or playing
        AudioSource _musicOutgoing; // the track fading out
        MusicTrack _track = MusicTrack.None;
        float _fade = 1f;

        static AudioDirector Instance
        {
            get
            {
                if (_instance == null) Create();
                return _instance;
            }
        }

        static void Create()
        {
            var host = new GameObject("[Audio]");
            DontDestroyOnLoad(host);
            _instance = host.AddComponent<AudioDirector>();

            // The UI-only scene may have no camera listener; without one nothing is audible.
            if (FindFirstObjectByType<AudioListener>() == null) host.AddComponent<AudioListener>();

            for (int i = 0; i < Voices; i++)
            {
                var voice = host.AddComponent<AudioSource>();
                voice.playOnAwake = false;
                _instance._voices.Add(voice);
                _instance._voiceGain.Add(1f);
            }

            _instance._music = NewMusicSource(host);
            _instance._musicOutgoing = NewMusicSource(host);

            foreach (Sfx sfx in Enum.GetValues(typeof(Sfx)))
            {
                var clip = Resources.Load<AudioClip>($"Audio/sfx_{Snake(sfx.ToString())}");
                if (clip != null) _instance._clips[sfx] = clip;
            }

            if (_instance._clips.Count == 0)
                Debug.LogWarning("[EmberDeck] No sound effects in Resources/Audio. Run art/audio/synth.py.");
        }

        static AudioSource NewMusicSource(GameObject host)
        {
            var source = host.AddComponent<AudioSource>();
            source.playOnAwake = false;
            source.loop = true;
            source.volume = 0f;
            return source;
        }

        public static void Play(Sfx sfx, float volume = 1f, float pitch = 1f, float pitchJitter = 0.04f)
        {
            var director = Instance;
            if (!director._clips.TryGetValue(sfx, out var clip)) return;

            float now = Time.unscaledTime;
            if (director._lastPlayed.TryGetValue(sfx, out float last) && now - last < MinRepeatGap) return;
            director._lastPlayed[sfx] = now;

            int index = director._nextVoice;
            director._nextVoice = (index + 1) % Voices;

            var voice = director._voices[index];
            director._voiceGain[index] = Mathf.Clamp01(volume);
            voice.clip = clip;
            // A few percent of pitch variation is what stops the tenth identical hit sounding
            // like a recording of the first.
            voice.pitch = pitch * (1f + UnityEngine.Random.Range(-pitchJitter, pitchJitter));
            voice.volume = director.SfxGain * director._voiceGain[index];
            voice.Play();
        }

        public static void PlayMusic(MusicTrack track)
        {
            var director = Instance;
            if (track == director._track) return;
            director._track = track;

            var clip = track == MusicTrack.None
                ? null
                : Resources.Load<AudioClip>($"Audio/music_{track.ToString().ToLowerInvariant()}");

            (director._music, director._musicOutgoing) = (director._musicOutgoing, director._music);
            director._music.clip = clip;
            director._music.volume = 0f;
            if (clip != null) director._music.Play();
            else director._music.Stop();
            director._fade = 0f;
        }

        float SfxGain => Muted ? 0f : MasterVolume * SfxVolume;

        void Update()
        {
            if (Input.GetKeyDown(KeyCode.M)) Muted = !Muted;

            float musicGain = Muted ? 0f : MasterVolume * MusicVolume;
            _fade = Mathf.MoveTowards(_fade, 1f, Time.unscaledDeltaTime / CrossfadeSeconds);
            _music.volume = musicGain * _fade;
            _musicOutgoing.volume = musicGain * (1f - _fade);
            if (_fade >= 1f && _musicOutgoing.isPlaying) _musicOutgoing.Stop();

            float sfxGain = SfxGain;
            for (int i = 0; i < Voices; i++)
                _voices[i].volume = sfxGain * _voiceGain[i];
        }

        static string Snake(string pascal)
        {
            var builder = new StringBuilder();
            for (int i = 0; i < pascal.Length; i++)
            {
                char c = pascal[i];
                if (char.IsUpper(c) && i > 0) builder.Append('_');
                builder.Append(char.ToLowerInvariant(c));
            }
            return builder.ToString();
        }
    }
}
