using System.Collections.Generic;
using EmberDeck.Core;
using UnityEngine;

namespace EmberDeck.Run
{
    /// <summary>
    /// The branching path through a run.
    ///
    /// Generated by walking several paths from the bottom row to the top rather than by
    /// scattering nodes and hoping they connect. Walking guarantees the two properties the
    /// map must have and that random placement keeps breaking: every node is reachable, and
    /// every node has somewhere to go. A map with a dead end is a run that ends in a wall.
    /// </summary>
    public sealed class RunMap
    {
        public const int Rows = 9;
        public const int Columns = 5;
        public const int Paths = 4;

        public readonly List<List<MapNode>> Grid = new();
        public MapNode Boss { get; private set; }

        /// <summary>Null before the first choice; otherwise where the player currently stands.</summary>
        public MapNode Current;

        public static RunMap Generate(DeterministicRng rng)
        {
            var map = new RunMap();
            var slots = new MapNode[Rows, Columns];

            for (int path = 0; path < Paths; path++)
            {
                int column = rng.Range(0, Columns);
                MapNode previous = null;

                for (int row = 0; row < Rows; row++)
                {
                    slots[row, column] ??= new MapNode { Row = row, Column = column };
                    var node = slots[row, column];

                    if (previous != null && !previous.Next.Contains(node))
                        previous.Next.Add(node);

                    previous = node;
                    // Drift by at most one column per row. More than that produces crossing
                    // lines the player cannot trace with their eye.
                    column = Mathf.Clamp(column + rng.Range(-1, 2), 0, Columns - 1);
                }
            }

            WidenNarrowRows(slots, rng);

            for (int row = 0; row < Rows; row++)
            {
                var line = new List<MapNode>();
                for (int column = 0; column < Columns; column++)
                    if (slots[row, column] != null) line.Add(slots[row, column]);
                map.Grid.Add(line);
            }

            map.Boss = new MapNode { Row = Rows, Column = Columns / 2, Type = NodeType.Boss };
            foreach (var node in map.Grid[Rows - 1])
                node.Next.Add(map.Boss);

            map.AssignTypes(rng);
            return map;
        }

        /// <summary>
        /// Guarantees every row offers at least two nodes.
        ///
        /// Path walking can converge all four paths onto one column, and a row with a single
        /// node is a map that stops being a map for that floor — the player is told to choose
        /// and given one option. An audit over 500 maps is what surfaced this; a single map
        /// looks fine.
        /// </summary>
        static void WidenNarrowRows(MapNode[,] slots, DeterministicRng rng)
        {
            for (int row = 0; row < Rows; row++)
            {
                int count = 0, occupied = -1;
                for (int column = 0; column < Columns; column++)
                    if (slots[row, column] != null) { count++; occupied = column; }
                if (count >= 2) continue;

                int target = occupied > 0 && (occupied == Columns - 1 || rng.Chance(0.5f))
                    ? occupied - 1
                    : occupied + 1;
                target = Mathf.Clamp(target, 0, Columns - 1);
                if (target == occupied) continue;

                var added = new MapNode { Row = row, Column = target };
                slots[row, target] = added;

                // Wire it in both directions, or it becomes the dead end it was meant to fix.
                if (row > 0)
                {
                    bool linked = false;
                    for (int column = 0; column < Columns; column++)
                    {
                        var parent = slots[row - 1, column];
                        if (parent == null || Mathf.Abs(column - target) > 1) continue;
                        parent.Next.Add(added);
                        linked = true;
                    }
                    if (!linked)
                        for (int column = 0; column < Columns && !linked; column++)
                            if (slots[row - 1, column] != null) { slots[row - 1, column].Next.Add(added); linked = true; }
                }

                if (row < Rows - 1)
                {
                    for (int column = 0; column < Columns; column++)
                    {
                        var child = slots[row + 1, column];
                        if (child == null || Mathf.Abs(column - target) > 1) continue;
                        added.Next.Add(child);
                    }
                    if (added.Next.Count == 0)
                        for (int column = 0; column < Columns && added.Next.Count == 0; column++)
                            if (slots[row + 1, column] != null) added.Next.Add(slots[row + 1, column]);
                }
            }
        }

        /// <summary>
        /// Types are placed by rule, not by pure weight. The first row is always a fight so
        /// a run opens the same way every time, and the row below the boss is always a rest
        /// so the hardest fight is never met at 6 HP through no choice of the player's.
        /// </summary>
        void AssignTypes(DeterministicRng rng)
        {
            for (int row = 0; row < Grid.Count; row++)
            {
                foreach (var node in Grid[row])
                {
                    if (row == 0) { node.Type = NodeType.Fight; continue; }
                    if (row == Grid.Count - 1) { node.Type = NodeType.Rest; continue; }

                    int roll = rng.Range(0, 100);
                    // Elites are barred from the first third: they are a choice to take a
                    // risk for a better reward, and that is not a choice with a starter deck.
                    bool elitesAllowed = row >= Grid.Count / 3;

                    node.Type = roll switch
                    {
                        < 55 => NodeType.Fight,
                        < 70 => elitesAllowed ? NodeType.Elite : NodeType.Fight,
                        < 80 => NodeType.Rest,
                        _    => NodeType.Treasure,
                    };
                }
            }
        }

        /// <summary>Nodes the player may move to right now.</summary>
        public IEnumerable<MapNode> Available()
        {
            if (Current == null)
            {
                foreach (var node in Grid[0]) yield return node;
                yield break;
            }
            foreach (var node in Current.Next) yield return node;
        }

        public bool IsAvailable(MapNode node)
        {
            foreach (var candidate in Available())
                if (candidate == node) return true;
            return false;
        }
    }
}
