using System.Text;
using EmberDeck.Content;
using UnityEditor;
using UnityEngine;

namespace EmberDeck.EditorTools
{
    /// <summary>
    /// Prints every card beside its upgrade.
    ///
    /// Upgrades are generated by rule, and a rule can produce something technically different
    /// but not worth a rest site — a +1 on a number nobody reads. Reading the sixty pairs side by
    /// side is the only way to judge that; the generator can only catch upgrades that are identical.
    /// </summary>
    public static class UpgradeAudit
    {
        [MenuItem("EmberDeck/Audit Upgrades")]
        public static void Audit()
        {
            var config = AssetDatabase.LoadAssetAtPath<RunConfig>("Assets/EmberDeck/Content/RunConfig.asset");
            if (config == null)
            {
                Debug.LogError("[EmberDeck] RunConfig not found. Generate content first.");
                return;
            }

            var report = new StringBuilder();
            int total = 0, missing = 0, costDrops = 0;
            report.AppendLine("=== Upgrade audit ===");

            foreach (var card in config.AllCards)
            {
                if (card == null || card.IsUpgraded) continue;
                total++;

                var plus = card.Upgrade;
                if (plus == null)
                {
                    missing++;
                    report.AppendLine($"{card.Id}: NO UPGRADE");
                    continue;
                }

                if (plus.Cost < card.Cost) costDrops++;
                report.AppendLine($"{card.DisplayName} [{card.Cost}] {Flatten(card.BuildDescription())}");
                report.AppendLine($"  -> {plus.DisplayName} [{plus.Cost}] {Flatten(plus.BuildDescription())}");
            }

            report.AppendLine($"cards {total}, missing upgrades {missing} (must be 0), cost reductions {costDrops}");
            Debug.Log(report.ToString());
        }

        static string Flatten(string text) => text.Replace("\n", " / ");
    }
}
